#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l vmem=1gb
#PBS -l walltime=0:10:00
#PBS -N networkneuro-agg
#PBS -V

#singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/main
#if [ ! -s output.mat ]; then
#	echo "output missing"
#	exit 1
##fi

./aggregate.py
